### ISSUE TITLE
Unable to create custom BOM component

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#231] opened 2024-05-06 20:46 UTC
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/445848d6-62a2-4c7e-a5f3-7787429952ed)

**Comment by Reyzerbit** [comment] 2024-05-07 20:59
Duplicate of #212

**Closed as completed by Reyzerbit** 2024-05-07 20:59 UTC
Labels: bug
