### ISSUE TITLE
Bug: 2.0 Weights calculating inconsistently. 

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#322] opened 2024-07-08 18:43 UTC
custom planter added via 1100 and modifying dims

72x24x12"H (.125"), 1.5" lips, 1" skids
Initial weight calc was ~25.3lbs
after toggling dims not calculating at 13.21lbs (empty)

after line copy the new and old line item are showing 58.64lbs

ALSO - weights are not calculating accurately. 35.45sf x 1.81lbs/sf = 64.1645lbs - ORE3D calculating at ~58lbs

**Comment by Reyzerbit** [comment] 2024-07-09 17:24
Duplicate of #316

**Closed as completed by Reyzerbit** 2024-07-09 17:24 UTC
Labels: bug
