### ISSUE TITLE
Feature: Reduce Decimal Places

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#146] opened 2024-04-02 15:11 UTC
Reduce decimal points in all Ore3D and NetSuite fields.

NetSuite Weight: round to nearest 1.0 lb.

All other decimals to .001

**Comment by Reyzerbit** [comment] 2024-04-02 15:20
Duplicate of [Ore3D Issue #930](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/issues/930)

**Closed as completed by Reyzerbit** 2024-04-02 15:20 UTC
Labels: enhancement
