### ISSUE TITLE
Bug: Proposal 50440 first line description issue

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#363] opened 2024-08-26 21:30 UTC
**Bug:**
Proposal 50440 had the first line item's description completely overridden 
![image](https://github.com/user-attachments/assets/370005e1-2262-4a3e-8b0b-8031a3ff968d)
I had to go in an fix it since it is a live proposal. This happens occasionally and I can't predict when it does happen.

After a Save Cycle the first line item will be overridden to a "-" character.

**Comment by Reyzerbit** [comment] 2024-08-27 15:25
Duplicate of Ore-Design/Ore-3D-Reports-Changelog#1200

**Closed as completed by Reyzerbit** 2024-08-27 15:25 UTC
Labels: bug
