### ISSUE TITLE
Make catalog items searchable

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#31] opened 2024-02-28 21:54 UTC
Unable to search catalog items by name.

This is a function available in ORE3D-1. 
Can this transfer to ORE3D-2?

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/e6b68e59-e030-419a-985c-9648d445f49f)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/8e8cae1b-0251-4171-928a-f03e4f07db6b)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/a701d768-0a80-4a47-9075-769da416b825)

**Comment by daniel11088** [comment] 2024-02-28 21:58
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/70411b1f-b6b7-4acc-aa12-20fdce93e076)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/d59d178c-46ac-4590-baf0-6b69a34e14fe)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/008bba9d-3830-44e9-a084-383c96b0b9b1)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/c173b018-ef80-4512-88ab-c975c8841b5a)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/8c3b9bfa-8ee3-4785-af20-8b2a9803ce0b)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/5c0e67f8-e794-4d9c-96ff-62072184b256)

**Comment by Reyzerbit** [comment] 2024-02-28 22:31
Duplicate of #12

**Closed as completed by Reyzerbit** 2024-02-28 22:31 UTC
Labels: bug
