### ISSUE TITLE
4040s glass surrounds are not working correctly.

### ISSUE THREAD

**Issue by jdrake89** [Ore-Design/Ore3DInternal-Reports-Changelog#50] opened 2024-03-15 14:27 UTC
The glass surrounds for the 4040 propane panel fire features are showing modified with incorrect dims. 

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/136127203/11b13496-f60b-46b9-ac85-3fa5769de3e9)

**Comment by Reyzerbit** [comment] 2024-03-15 16:31
Duplicate of #49

**Closed as completed by Reyzerbit** 2024-03-15 16:31 UTC
Labels: bug
