### ISSUE TITLE
FUSE Rec not calculating correctly

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#29] opened 2024-02-28 17:41 UTC
FAB time looks like it is always calculating for a skid and finish time changes.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/284a7a94-a865-49c9-97c1-c40f34b66249)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/5d0093f1-bed6-4b6f-ab40-a0d9f2b68316)

**Comment by daniel11088** [comment] 2024-02-28 17:42
ORE3D V1

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/08e577af-ab64-45f9-868c-2f06a40c2d0f)

**Comment by Reyzerbit** [comment] 2024-02-28 17:45
@daniel11088 I will need ALL build data to resolve this issue. Please save both of these proposals in their respective versions, and send me the two proposal numbers.

**Comment by daniel11088** [comment] 2024-02-28 17:56
@Reyzerbit 
46776 in ore1
47314 in ore2

**Comment by Reyzerbit** [comment] 2024-02-28 18:46
Issue caused by mismatching reveal type (Ore3D is adding time for reveal even if reveal is set to "None"). This will be fixed in next update.

**Comment by Reyzerbit** [comment] 2024-03-04 22:37
Resolved in [Release 1.0.10](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.10)

**Closed as completed by Reyzerbit** 2024-03-04 22:37 UTC
Labels: bug, in progress
