### ISSUE TITLE
Bug: Abstract BOM Items Rounding

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#297] opened 2024-06-05 15:03 UTC
**Bug:**
Created an Abstract build with Decimal Points in the material BOM items 
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/b03f8af2-c018-4922-a89f-51855fcf9ba8)
After saving it and opening it back up. it moved all my bom item QTY to whole numbers and zero'd out some
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/de57e41f-1823-4eea-b8e8-65f4eeb5be30)

We need to have it stay exactly as imputed before saving.

**Comment by CBarsell** [comment] 2024-06-05 15:05
Also happens when copying an abstract Item
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/133701810/6b84e0d1-06fc-45cf-bdc9-148c59934311)

**Comment by Reyzerbit** [comment] 2024-06-05 18:46
Duplicate of Ore-Design/Ore-3D-Reports-Changelog#1079

**Closed as completed by Reyzerbit** 2024-06-05 18:46 UTC
Labels: bug
