### ISSUE TITLE
Feature: Receipts Panel UI

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore3DInternal-Reports-Changelog#255] opened 2024-05-16 16:04 UTC
**Issue:**
Please add the QTY to the columns and individual price as well as total line item price
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/2c219e37-63c3-450b-8e22-64f384e80c11)

**Comment by Reyzerbit** [comment] 2024-05-16 17:19
Duplicate of #250

**Closed as completed by Reyzerbit** 2024-05-16 17:19 UTC
Labels: enhancement
