### ISSUE TITLE
Bug: Unable to convert 2.0 proposal to SO

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#114] opened 2024-03-26 20:54 UTC
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/67e7bb88-3247-409c-ab7f-2db8195ba869)

REF: 47963

**Comment by Reyzerbit** [comment] 2024-03-27 15:23
Duplicate of #120

**Closed as completed by Reyzerbit** 2024-03-27 15:23 UTC
Labels: bug
