### ISSUE TITLE
Individual price and total price per line item

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#190] opened 2024-04-11 15:14 UTC
Can we get a price break down, similar to 1.0, that shows the individual price along with total price?

I found that the A1206 predesign is not calculating correctly.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/5c0cf743-84d2-427d-bd8e-e44496517065)
 

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/88089aa0-b1bb-4753-a8dd-6a173b9d2c26)

**Comment by Reyzerbit** [comment] 2024-04-11 19:32
Duplicate of #189

**Closed as completed by Reyzerbit** 2024-04-11 19:32 UTC
Labels: bug
