### ISSUE TITLE
Feature: Add Yellow Boarder Error if Main Description is Overriden

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#176] opened 2024-04-08 17:14 UTC
Add Yellow Boarder Error if Main Description is Overriden

**Comment by Reyzerbit** [comment] 2024-04-08 17:25
Duplicate of [Ore3D Issue 907](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/issues/907)

**Closed as completed by Reyzerbit** 2024-04-08 17:25 UTC
Labels: enhancement
