### ISSUE TITLE
Yield appears to be subtracted from total SQF instead of added

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#83] opened 2024-03-18 20:03 UTC
This should be a 5 sqft of material + Yield.

12x12x12 rec is 5 sq ft.

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/fc3b7a38-4833-4cd1-9f1e-ea0e4fcf8639)

**Comment by Reyzerbit** [comment] 2024-03-18 20:04
Duplicate of #72

**Closed as completed by Reyzerbit** 2024-03-18 20:04 UTC
Labels: bug
