### ISSUE TITLE
Planter description in customer facing description

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore3DInternal-Reports-Changelog#202] opened 2024-04-19 15:46 UTC
How can we get the planter description to show up in the description like in 1.0?

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/864c31af-bcb0-411d-9998-2ce170e4eac8)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/26dcf741-d841-41c6-8267-b373f101d153)

**Comment by Reyzerbit** [comment] 2024-04-19 17:13
Duplicate of #188

**Closed as completed by Reyzerbit** 2024-04-19 17:13 UTC
Labels: bug
