### ISSUE TITLE
Bug: PreDesign Not Configuring Proporly

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore3DInternal-Reports-Changelog#1] opened 2024-02-19 15:32 UTC
A1200 - defaults to having welded feet - incorrect, should be skirt. 

REF: A1110-SLCT

NetSuite item sets reveal as Skid.
Ore3D defaults to skirt: Incorrectly identifies as pre-designed (with skid)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/37abe2af-79a2-42c1-9884-94ccc4f924f6)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114440644/caae9411-0504-4e33-9940-b877a4dc6921)

**Comment by CBarsell** [comment] 2024-02-19 20:05
Noticed this on multiple other Catalog products. There's multiple that pull in the wrong type of reveal/wrong reveal Height measurement

**Comment by Reyzerbit** [comment] 2024-02-22 19:07
Issue is caused by changes to reveal types on round products. A fix will be implemented.

**Comment by Reyzerbit** [comment] 2024-02-28 16:23
Fixed in [Release 1.0.9](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/releases/tag/1.0.9)

**Closed as completed by Reyzerbit** 2024-02-28 16:23 UTC
Labels: bug, in progress
