### ISSUE TITLE
Bug: 1.0 to 2.0 copy - Lip material calculating not matching

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore3DInternal-Reports-Changelog#122] opened 2024-03-27 16:32 UTC
When copying a proposal from 1.0 to 2.0 material not matching on planter with lips. 

1.0 Example
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/e9f37350-78d9-4469-b344-834b83c23341)

2.0 Example
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114424580/b13117b7-5a43-44e1-b287-5e417eaeb612)

**Comment by Reyzerbit** [comment] 2024-03-27 17:24
Duplicate of #124

**Closed as completed by Reyzerbit** 2024-03-27 17:24 UTC
Labels: bug

**Comment by Reyzerbit** [comment] 2024-03-27 18:28
Not resolved, seems to be intermittent, keep an eye out.
